pullRequestOpened: >
  Thank you for opening this pull request, your code will be reviewed soon! 
  
  Reminder, please follow the <a href="https://github.com/brittanyrw/emojiscreen/tree/master#contributing-">contribution guidelines</a> outlined in the README.md
  
  This Pull Request should be closing an Issue that you have been assigned. 
  
  If any updates need to be made, we will leave a comment for you here outlining exactly what you need to change for your pull request to be accepted. 💖
